#pragma once

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#include "oGL/GL.h"
#include "oGL/glext.h"

bool InitializeOpenGLExtensions();

extern PFNGLACTIVETEXTUREPROC pglActiveTexture;
extern PFNGLATTACHSHADERPROC pglAttachShader;
extern PFNGLBINDATTRIBLOCATIONPROC pglBindAttribLocation;
extern PFNGLBINDBUFFERPROC pglBindBuffer;
extern PFNGLBINDFRAMEBUFFERPROC pglBindFramebuffer;
extern PFNGLBINDRENDERBUFFERPROC pglBindRenderbuffer;
extern PFNGLBINDVERTEXARRAYPROC pglBindVertexArray;
extern PFNGLBLITFRAMEBUFFERPROC pglBlitFramebuffer;
extern PFNGLBUFFERDATAPROC pglBufferData;
extern PFNGLCHECKFRAMEBUFFERSTATUSPROC pglCheckFramebufferStatus;
extern PFNGLCOMPILESHADERPROC pglCompileShader;
extern PFNGLCREATEPROGRAMPROC pglCreateProgram;
extern PFNGLCREATESHADERPROC pglCreateShader;
extern PFNGLDELETEBUFFERSPROC pglDeleteBuffers;
extern PFNGLDELETEFRAMEBUFFERSPROC pglDeleteFramebuffers;
extern PFNGLDELETEPROGRAMPROC pglDeleteProgram;
extern PFNGLDELETERENDERBUFFERSPROC pglDeleteRenderbuffers;
extern PFNGLDELETESHADERPROC pglDeleteShader;
extern PFNGLDISABLEVERTEXATTRIBARRAYPROC pglDisableVertexAttribArray;
extern PFNGLENABLEVERTEXATTRIBARRAYPROC pglEnableVertexAttribArray;
extern PFNGLFRAMEBUFFERRENDERBUFFERPROC pglFramebufferRenderbuffer;
extern PFNGLFRAMEBUFFERTEXTURE2DPROC pglFramebufferTexture2D;
extern PFNGLGENBUFFERSPROC pglGenBuffers;
extern PFNGLGENFRAMEBUFFERSPROC pglGenFramebuffers;
extern PFNGLGENRENDERBUFFERSPROC pglGenRenderbuffers;
extern PFNGLGENVERTEXARRAYSPROC pglGenVertexArrays;
extern PFNGLGETATTRIBLOCATIONPROC pglGetAttribLocation;
extern PFNGLGETPROGRAMINFOLOGPROC pglGetProgramInfoLog;
extern PFNGLGETPROGRAMIVPROC pglGetProgramiv;
extern PFNGLGETSHADERINFOLOGPROC pglGetShaderInfoLog;
extern PFNGLGETSHADERIVPROC pglGetShaderiv;
extern PFNGLGETUNIFORMLOCATIONPROC pglGetUniformLocation;
extern PFNGLLINKPROGRAMPROC pglLinkProgram;
extern PFNGLRENDERBUFFERSTORAGEPROC pglRenderbufferStorage;
extern PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC pglRenderbufferStorageMultisample;
extern PFNGLSHADERSOURCEPROC pglShaderSource;
extern PFNGLUNIFORM1FPROC pglUniform1f;
extern PFNGLUNIFORM1IPROC pglUniform1i;
extern PFNGLUNIFORM1IVPROC pglUniform1iv;
extern PFNGLUNIFORM2FPROC pglUniform2f;
extern PFNGLUNIFORM4FPROC pglUniform4f;
extern PFNGLUSEPROGRAMPROC pglUseProgram;
extern PFNGLVERTEXATTRIBPOINTERPROC pglVertexAttribPointer;

#define glActiveTexture pglActiveTexture
#define glAttachShader pglAttachShader
#define glBindAttribLocation pglBindAttribLocation
#define glBindBuffer pglBindBuffer
#define glBindFramebuffer pglBindFramebuffer
#define glBindRenderbuffer pglBindRenderbuffer
#define glBindVertexArray pglBindVertexArray
#define glBlitFramebuffer pglBlitFramebuffer
#define glBufferData pglBufferData
#define glCheckFramebufferStatus pglCheckFramebufferStatus
#define glCompileShader pglCompileShader
#define glCreateProgram pglCreateProgram
#define glCreateShader pglCreateShader
#define glDeleteBuffers pglDeleteBuffers
#define glDeleteFramebuffers pglDeleteFramebuffers
#define glDeleteProgram pglDeleteProgram
#define glDeleteRenderbuffers pglDeleteRenderbuffers
#define glDeleteShader pglDeleteShader
#define glDisableVertexAttribArray pglDisableVertexAttribArray
#define glEnableVertexAttribArray pglEnableVertexAttribArray
#define glFramebufferRenderbuffer pglFramebufferRenderbuffer
#define glFramebufferTexture2D pglFramebufferTexture2D
#define glGenBuffers pglGenBuffers
#define glGenFramebuffers pglGenFramebuffers
#define glGenRenderbuffers pglGenRenderbuffers
#define glGenVertexArrays pglGenVertexArrays
#define glGetAttribLocation pglGetAttribLocation
#define glGetProgramInfoLog pglGetProgramInfoLog
#define glGetProgramiv pglGetProgramiv
#define glGetShaderInfoLog pglGetShaderInfoLog
#define glGetShaderiv pglGetShaderiv
#define glGetUniformLocation pglGetUniformLocation
#define glLinkProgram pglLinkProgram
#define glRenderbufferStorage pglRenderbufferStorage
#define glRenderbufferStorageMultisample pglRenderbufferStorageMultisample
#define glShaderSource pglShaderSource
#define glUniform1f pglUniform1f
#define glUniform1i pglUniform1i
#define glUniform1iv pglUniform1iv
#define glUniform2f pglUniform2f
#define glUniform4f pglUniform4f
#define glUseProgram pglUseProgram
#define glVertexAttribPointer pglVertexAttribPointer
